import { Geist, Geist_Mono, Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const montserratAlt = Montserrat_Alternates({
  variable: "--font-mont-alt",
  subsets: ["latin"],
  weight: '500'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],

});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserratAlt.className} h-full antialiased`}
    >

      <body className={`min-h-full flex flex-col ${montserratAlt.className} bg-[#424B54]`}>{children}</body>
    </html>
  );
}
